### ISSUE TITLE
[BUG] Multi-select in admin panel view

### ISSUE THREAD

**Issue by belkin** [amici-infotech/craft-super-dynamic-fields#1]
Hi,

I have a Multi-select field and everything is working fine until you add this field in panel view:
![image](https://user-images.githubusercontent.com/3419659/95174752-caa42a80-07ba-11eb-9409-2a79e552ebc2.png)
![image](https://user-images.githubusercontent.com/3419659/95174776-d7288300-07ba-11eb-8182-c0a4a39287ee.png)

Then you get 500 error if you try to view this section or user group. In the network tab I'm getting more details over de error:
http://local.hisk.edu/index.php?p=admin/actions/element-indexes/get-elements&v=1601971401500
`{"error":"An exception has been thrown during the rendering of a template (\"Array to string `conversion\")."}`

I found the reason but unable to fix complete: 
On vendor/amici/craft-super-dynamic-fields/src/base/FieldSettings.php, line 274.
I have added above the return this code:
`if (\Craft::$app->getRequest()->getIsCpRequest()) {
    return implode(", ", $return);
}`
And it seemed to be working fine except new data were unable to be saved in that field.

**Comment by amici-infotech** [comment]
Hey @belkin I have solved the issue. Can you please upgrade SDF plugin and confirm this?

**Comment by belkin** [comment]
Yes, thanks for the fast response and fix! :)
