### ISSUE TITLE
graphql support

### ISSUE THREAD

**Issue by peaffenzeller** [amici-infotech/craft-super-dynamic-fields#2]
hello,

I'm using craft as headless CMS and consider fetching the data with graphql, but apparently, the super-dynamic fields don't work with graphql - the returned value is always just an empty string (tested in graphiql).
I would definitely need this to work if I want to continue using graphql.
do you plan to support graphql sometime soon?

best,
peter

**Comment by amici-infotech** [comment]
Hey, I have added GraphQL support in v1.0.6
![image](https://user-images.githubusercontent.com/20450552/130608097-82c2ffe8-6131-4100-9c23-0a2e03bf96cc.png)

**Comment by peaffenzeller** [comment]
awesome, thank you!
