### ISSUE TITLE
Accessing sibling field within matrix block

### ISSUE THREAD

**Issue by tigerchick** [amici-infotech/craft-super-dynamic-fields#4]
Hi, I'd like to use this to populate a checkbox list with items from another field contained within the same matrix block as a dynamic field. Is this possible? 
It should be a case of being able to identify the current "parent" matrix block and then using that to query the sibling field.
I guess that the entry will have to have been saved at least once in order to access the block.
Any thoughts much appreciated!

**Comment by amici-infotech** [comment]
@tigerchick I am bit confuse. Can you share screenshots to explain it more?

**Comment by tigerchick** [comment]
I don't think a screenshot will help. I shall try explaining again though.
I have a matrix block:
Within the matrix block are two fields: a super table field (with an entry field inside it) and a superdynamic checkbox field.
I want the superdynamic field to be populated with json values derived from the supertable>entry field.

**Comment by tigerchick** [comment]
I was able to achieve my use case by using Lewis Jenkins' craft-dynamic-fields instead.  Within that plugin he exposes an 'element' variable that allows me to query the matrix block or entry if not within matrix. When in matrix, 'element.owner' allows me to query the entry.
Perhaps this could be a feature request?  Thank you for your time in considering this.

**Comment by amici-infotech** [comment]
@tigerchick Yep. Nice feature to add. Will updated it early next week. Thanks.

**Comment by amici-infotech** [comment]
@tigerchick We have added new `current` option in `v2.0.0.1` (Craft 4) and `v1.0.7.1` (Craft 3). You can use that object to get various informations including element. Example:

```
{% set superTable = current.element.superTable ?? null %}
[
    { "label" : "-- Select -- ", "value": "" }
    {% for item in superTable %}
    ,{ "label" : "{{ item.test1 }}", "value": "{{ item.test1 }}" }
    {% endfor %}
]
```

I would use it with cache like this:
```
{% set id = current.element.getId()|default("global") %}
{% cache using key id %}
    {% set superTable = current.element.superTable ?? null %}
    [
        { "label" : "-- Select -- ", "value": "" }
        {% for item in superTable %}
        ,{ "label" : "{{ item.test1 }}", "value": "{{ item.test1 }}" }
        {% endfor %}
    ]
{% endcache %}

```

**Comment by tigerchick** [comment]
Awesome! Very nice - thanks for adding.
